"""MCP client wrapper for octobrain (stdio transport).

We talk to octobrain via the official MCP Python SDK over stdio. Stdio is
simpler than the streamable-HTTP transport for benchmarks: no port binding,
no health checks, no race conditions. The SDK spawns octobrain as a child
process and routes JSON-RPC over its stdin/stdout.

Public surface is intentionally small — `memorize` and `remember` only.
Everything else (decay, consolidation, sleep cycles) runs automatically
inside octobrain and the client doesn't need to know.
"""
from __future__ import annotations

import asyncio
import os
from pathlib import Path
from typing import Optional

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client


class OctobrainClient:
    """Synchronous facade over the async MCP session.

    Spawns `octobrain mcp` as a child, connects via stdio, exposes memorize /
    remember as plain method calls. Each call runs the async body on a private
    event loop so the rest of the benchmark stays synchronous.
    """

    def __init__(
        self,
        data_dir: Path,
        binary: str = "octobrain",
        extra_env: Optional[dict[str, str]] = None,
    ) -> None:
        self._data_dir = Path(data_dir)
        self._data_dir.mkdir(parents=True, exist_ok=True)

        # Octobrain reads its config + data under $XDG_DATA_HOME/octobrain.
        xdg_data_home = self._data_dir / "xdg"
        octobrain_dir = xdg_data_home / "octobrain"
        octobrain_dir.mkdir(parents=True, exist_ok=True)

        # Write a config.toml so the embedding stack is explicit + deterministic
        # rather than relying on octobrain's bundled template defaults.
        self._write_octobrain_config(octobrain_dir / "config.toml")

        env = dict(os.environ)
        env["XDG_DATA_HOME"] = str(xdg_data_home)
        env["HOME"] = str(self._data_dir / "home")
        Path(env["HOME"]).mkdir(parents=True, exist_ok=True)

        # Translate bench-local env vars into the standard names octolib's
        # embedding providers read. We keep them separate in .env so the chat
        # endpoint (Ollama Cloud) doesn't collide with the embedding endpoint
        # (OpenAI for apples-to-apples vs SOTA benchmarks).
        emb_key = os.environ.get("OCTOBRAIN_EMBEDDING_API_KEY")
        if emb_key:
            # Used by octolib's openai / voyage / jina / google providers.
            env["OPENAI_API_KEY"] = emb_key
            env["VOYAGE_API_KEY"] = emb_key
            env["JINA_API_KEY"] = emb_key
            env["GOOGLE_API_KEY"] = emb_key
        emb_base = os.environ.get("OCTOBRAIN_EMBEDDING_BASE_URL", "").strip()
        if emb_base:
            env["OPENAI_BASE_URL"] = emb_base
            env["OPENAI_API_BASE"] = emb_base  # legacy name some clients honor

        if extra_env:
            env.update(extra_env)

        self._server_params = StdioServerParameters(
            command=binary,
            args=["mcp"],
            env=env,
        )

    # ── config generation ────────────────────────────────────────────────────

    def _write_octobrain_config(self, config_path: Path) -> None:
        """Write a minimal config.toml controlling the embedding stack only —
        everything else inherits octobrain's compiled defaults via #[serde(default)].
        """
        embedding_model = os.environ.get(
            "OCTOBRAIN_EMBEDDING_MODEL", "openai:text-embedding-3-small"
        )
        toml_text = f'''# Generated by the bench adapter — do not hand-edit.
[embedding]
model = "{embedding_model}"
batch_size = 32
max_tokens_per_batch = 100000

[search]
similarity_threshold = 0.3
max_results = 50

[search.hybrid]
enabled = true
default_vector_weight = 0.8
default_recency_weight = 0.1
default_importance_weight = 0.1
recency_decay_days = 30

[search.reranker]
enabled = false
model = "voyage:rerank-2.5"
top_k_candidates = 50
final_top_k = 10

[search.hyde]
enabled = true
top_k = 3
alpha = 0.5

[memory]
max_memories = 10000
auto_cleanup_days = 365
cleanup_min_importance = 0.1
max_search_results = 50
default_importance = 0.5
decay_enabled = true
decay_half_life_days = 90
access_boost_factor = 1.2
min_importance_threshold = 0.05
auto_linking_enabled = true
auto_link_threshold = 0.78
max_auto_links_per_memory = 5
bidirectional_links = true
stale_ref_cleanup_enabled = true
stale_ref_importance_penalty = 0.3

[knowledge]
chunk_size = 1200
chunk_overlap = 300
outdating_days = 15
max_results = 5
session_ttl_hours = 120
'''
        config_path.write_text(toml_text)
        self._loop: Optional[asyncio.AbstractEventLoop] = None
        self._session: Optional[ClientSession] = None
        self._stdio_ctx = None
        self._session_ctx = None

    # ── lifecycle ────────────────────────────────────────────────────────────

    def connect(self) -> None:
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        self._loop.run_until_complete(self._connect_async())

    async def _connect_async(self) -> None:
        self._stdio_ctx = stdio_client(self._server_params)
        read, write = await self._stdio_ctx.__aenter__()
        self._session_ctx = ClientSession(read, write)
        self._session = await self._session_ctx.__aenter__()
        await self._session.initialize()

    def disconnect(self) -> None:
        if self._loop is None:
            return
        try:
            self._loop.run_until_complete(self._disconnect_async())
        finally:
            self._loop.close()
            self._loop = None
            self._session = None
            self._stdio_ctx = None
            self._session_ctx = None

    async def _disconnect_async(self) -> None:
        if self._session_ctx is not None:
            try:
                await self._session_ctx.__aexit__(None, None, None)
            except Exception:
                pass
        if self._stdio_ctx is not None:
            try:
                await self._stdio_ctx.__aexit__(None, None, None)
            except Exception:
                pass

    def __enter__(self) -> "OctobrainClient":
        self.connect()
        return self

    def __exit__(self, *_exc) -> None:
        self.disconnect()

    # ── tool calls ───────────────────────────────────────────────────────────

    def memorize(
        self,
        title: str,
        content: str,
        memory_type: str = "communication",
        importance: float = 0.5,
        tags: Optional[list[str]] = None,
    ) -> str:
        """Store one memory. Returns the assistant text reply."""
        args: dict = {
            "title": title[:200],  # octobrain validates 5..200
            "content": content[:9990] if len(content) >= 10 else content + " (short turn)",
            "memory_type": memory_type,
            "importance": importance,
        }
        if tags:
            args["tags"] = tags[:10]
        return self._call_tool("memorize", args)

    def remember(self, query: str, limit: int = 5) -> str:
        """Semantic search. Returns the formatted text payload octobrain emits."""
        return self._call_tool(
            "remember",
            {"query": query, "limit": max(1, min(limit, 5))},
        )

    def _call_tool(self, name: str, arguments: dict) -> str:
        assert self._session is not None and self._loop is not None, "not connected"
        result = self._loop.run_until_complete(
            self._session.call_tool(name=name, arguments=arguments)
        )
        parts: list[str] = []
        for c in result.content or []:
            text = getattr(c, "text", None)
            if text:
                parts.append(text)
        return "\n".join(parts)
